---
- name: Determine OS
  set_fact:
    system_os: "{{ ansible_os_family }}"
    allowed_ports: "{{ ports | default('') }}"
    
- name: Allow incoming TCP ports for SMTP
  become: yes
  iptables:
    chain: INPUT
    protocol: TCP
    destination_port: "{{ item }}"
    jump: ACCEPT
    state: present
  loop: "{{ allowed_ports }}"
  when: system_os == "Debian"
  
- name: Restart ssh
  service:
    name: ssh
    state: restarted
  when: system_os == "Debian"



