---
- name: Determine OS
  set_fact:
    system_os: "{{ ansible_os_family }}"
    allowed_ports: "{{ ports | default('') }}"
    
- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow
- name: Open port on Ubuntu
  become: true
  ufw:
    rule: allow
    port: "{{ port }}"
    proto: tcp

- name: Restart ssh
  service:
    name: ssh
    state: restarted


- name: Execute command for Windows
  win_firewall_rule:
    name: Allow Port {{ item }}
    localport: "{{ item }}"
    direction: in
    protocol: tcp
    action: allow
    enabled: yes
  with_items: "{{ allowed_ports.split(',') }}"
  when: system_os == "Windows"

